---
- name: "apache modulo absent"
  apache2_module: name={{item}}  state=absent 
  with_items:
  - mpm_prefork
  - mpm_event

- name: "apache modulo present"
  apache2_module: name={{item}} state=present
  with_items:
  - fastcgi
  - actions
  - rewrite
  - deflate
  - expires
  - mpm_worker

- name: "apache - virtualhost {{usuario_wordpress}}"
  template: src=apache_wordpress.conf dest=/etc/apache2/sites-available/{{usuario_wordpress}}.conf owner=root mode=644 backup=yes
  register: virtualhost 
  when: aptget|success

- name: "a2ensite {{usuario_wordpress}].conf"
  file: src=/etc/apache2/sites-available/{{usuario_wordpress}}.conf dest=/etc/apache2/sites-enabled/{{usuario_wordpress}}.conf state=link
  when: virtualhost|success

- name: "ajustando o apache2.conf"
  template: src=apache2.conf dest=/etc/apache2/apache2.conf owner=www-data group=www-data mode=751 backup=yes

- name: "ajustando a permissão do apache2"
  file: path=/etc/apache2 owner=www-data group=www-data mode=0751 recurse=yes

- name: "restart apache"
  service: name=apache2 state=restarted

- name: "habilitando o apache2"
  service: name=apache2 enabled=yes

