---
# tasks file for wordpress
- include: adduser.yml
- include: apt-get.yml
- include: vsftpd.yml
- include: mysql.yml
  failed_when: True
  ignore_errors: True
- include: wordpress.yml
  tags: wordpress
- include: apache.yml
  tags: apache
- include: fail2ban.yml
- include: localtime.yml
