---
- name: "criando o arquivo ~/.my.cnf"
  template: src=my.cnf dest=~/.my.cnf owner=root mode=644 backup=yes
  register: mycnf

- name: "removendo o usuario anonymous localhost"
  mysql_user: name='' host=localhost state=absent
  when: mycnf|success

- name: "update mysql user default host ansible_hostname"
  mysql_user: name='' host={{ansible_hostname}} password={{mysql_password}}
  when: mycnf|success

- name: "update mysql root password for all root accounts"
  ignore_errors: yes
  mysql_user: name={{mysql_user}} host={{item}} password={{mysql_password}}
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  when: mycnf|success

- name: "create database"
  mysql_db: name={{database}} state=present

- name: "criando o usuario do wordpress no mysql"
  mysql_user: user={{usuario_wordpress}} password={{password_wordpress}} priv={{database}}.*:ALL state=present

